### PR TITLE
MIT license added #4

### PR DESCRIPTION
**Pull request by shalithasuranga**

### CODE REVIEW

**Comment by shalithasuranga** [comment]
What's the error "The Travis CI build failed". please advice

Thanks

**Comment by rehrumesh** [comment]
@shalithasuranga Ignore the build failure. Howevenr that is a seperate issue which we need help.

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
@shalithasuranga please use seperate branches for separate issues. :)

**Comment by shalithasuranga** [comment]
@rehrumesh  I understood it. Now I am familiar with scenario with multiple branching . Thanks for helping

**Pull request merged**
